[build]
  command = "npm run build"
  functions = "functions"
  publish = "client/build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
